/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui;

import com.blogspot.gameeaterpl.character.Ability;

/**
 *
 * @author sakurazuka
 */
public class AttributesFillRow extends javax.swing.JPanel {

    private String mName;
    private Integer mValue;

    /**
     * Creates new form AttributesFillRow
     */
    public AttributesFillRow() {
        mName = "";
        initComponents();
        this.setAttributeValue(3);
    }

    public AttributesFillRow(String pmName) {
        mName = pmName;
        initComponents();
        this.setAttributeValue(3);

    }

    /**
     * Ustawia wartości pól w wierszu
     *
     * @param pmValue
     */
    private void setAttributeValue(Integer pmValue) {
        this.mValue = pmValue;
        this.attributeValueField.setSelectedItem(pmValue);
        this.attributeModifierFIeld.setText(Ability.calculateModifier(pmValue).toString());
    }

    public void reset() {
        setAttributeValue(3);
    }

    public Integer getmValue() {
        return mValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AttributeRowLabel = new javax.swing.JLabel();
        attributeModifierFIeld = new com.blogspot.gameeaterpl.ui.AttributeTextField();
        attributeValueField = new javax.swing.JComboBox();

        AttributeRowLabel.setText(mName);

        attributeValueField.setModel(new javax.swing.DefaultComboBoxModel(new Integer[] { 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 }));
        attributeValueField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributeValueFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AttributeRowLabel)
                .addGap(13, 13, 13)
                .addComponent(attributeValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributeModifierFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(AttributeRowLabel)
                .addComponent(attributeModifierFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(attributeValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void attributeValueFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributeValueFieldActionPerformed
        this.mValue = (Integer) this.attributeValueField.getSelectedItem();
        this.attributeModifierFIeld.setText(Ability.calculateModifier(this.mValue).toString());
    }//GEN-LAST:event_attributeValueFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AttributeRowLabel;
    private com.blogspot.gameeaterpl.ui.AttributeTextField attributeModifierFIeld;
    private javax.swing.JComboBox attributeValueField;
    // End of variables declaration//GEN-END:variables
}
