/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels.windows;

import com.blogspot.gameeaterpl.enums.Skills;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.AbstractListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Sakurazuka
 */
public class SkillSelectionWindow extends javax.swing.JFrame {

    ArrayList<Skills> mRestrictedSkills; //Skille, w ktorych juz mamy Proficency
    ArrayList<Skills> mBaseSkills; //Lista Skilli, z których można wybierac

    private final Integer mMaxSelected;
    private final Integer mMinSelected;
    private final Integer mExatcSelected;
    private final SkillsSelectionWindowOpener mOpener;

    /**
     * Creates new form SkillSelectionWindow
     */
    public SkillSelectionWindow() {
        this.mOpener = null;
        this.mBaseSkills = null;
        this.mRestrictedSkills = new ArrayList<>();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.mMaxSelected = skillsList.getModel().getSize();
        this.mMinSelected = 0;
        mExatcSelected = null;

    }

    public SkillSelectionWindow(Integer pmMaxSelected, Integer pmMinSelected, SkillsSelectionWindowOpener pmOpener, ArrayList<Skills> pmRestricted, ArrayList<Skills> pmBase) {
        this.mOpener = pmOpener;

        this.mBaseSkills = pmBase; //może być nullem

        if (pmRestricted != null) {
            this.mRestrictedSkills = pmRestricted;
        } else {
            this.mRestrictedSkills = new ArrayList<>();
        }

        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        if (pmMaxSelected != null) {
            this.mMaxSelected = pmMaxSelected;
        } else {
            this.mMaxSelected = skillsList.getModel().getSize();
        }

        if (pmMinSelected != null) {
            this.mMinSelected = pmMinSelected;
        } else {
            this.mMinSelected = 0;
        }

        if (Objects.equals(mMinSelected, mMaxSelected)) {
            mExatcSelected = mMinSelected;
            if (mExatcSelected == 1) {
                skillsList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // jeśli możemy wybrać tylko 1 to tryb wyboru pojedynczego
            }
        } else {
            mExatcSelected = null;
        }
    }

    private AbstractListModel createListModel() {
        ArrayList<Skills> lvList;
        if (mBaseSkills == null) {
            lvList = Skills.toList();
        } else {
            lvList = mBaseSkills;
        }

        for (Skills lvSkill : mRestrictedSkills) {
            if (lvList.contains(lvSkill)) {
                lvList.remove(lvSkill);
            }
        }

        return new javax.swing.AbstractListModel() {
            Skills[] skills = new Skills[lvList.size()];
            {
                this.skills = lvList.toArray(skills);
            }

            @Override
            public int getSize() {
                return skills.length;
            }

            @Override
            public Object getElementAt(int i) {
                return skills[i];
            }
        };

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        skillsList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("jLabel1");

        skillsList.setModel(createListModel());
        jScrollPane1.setViewportView(skillsList);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkillSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkillSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkillSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkillSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkillSelectionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList skillsList;
    // End of variables declaration//GEN-END:variables
}
