/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.character.Character;

/**
 *
 * @author sakurazuka
 */
public class AttributesTabbedPanel extends javax.swing.JPanel implements CharacterCreatorPanel {

    /**
     * Creates new form AttributesTabbedPanel
     */
    public AttributesTabbedPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        attributesFillPanel2 = new com.blogspot.gameeaterpl.ui.panels.AttributesFillPanel();
        atributesPanel1 = new com.blogspot.gameeaterpl.ui.panels.AtributesPanel();
        attributesPointsPanel1 = new com.blogspot.gameeaterpl.ui.panels.AttributesPointsPanel();

        jTabbedPane1.addTab("Fill Scores", attributesFillPanel2);
        jTabbedPane1.addTab("Generate Scores", atributesPanel1);
        jTabbedPane1.addTab("Distribute Points", attributesPointsPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.blogspot.gameeaterpl.ui.panels.AtributesPanel atributesPanel1;
    private com.blogspot.gameeaterpl.ui.panels.AttributesFillPanel attributesFillPanel2;
    private com.blogspot.gameeaterpl.ui.panels.AttributesPointsPanel attributesPointsPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fillCharacterObject(Character pmCharacter) {
        ((CharacterCreatorPanel)jTabbedPane1.getSelectedComponent()).fillCharacterObject(pmCharacter);
    }
}
