/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.character.DraconicAncestorColor;
import com.blogspot.gameeaterpl.enums.DamageType;
import com.blogspot.gameeaterpl.mechanics.AutomaterAttack;
import com.blogspot.gameeaterpl.ui.panels.windows.DragonColorSelectionWindow;

/**
 *
 * @author sakurazuka
 */
public class DragonbornOptionalRaceChoicePanel extends javax.swing.JPanel {

    DraconicAncestorColor mSelectedColor;
    DamageType mDamageType;
    AutomaterAttack mAttack;
    
    /**
     * Creates new form DragonbornOptionalRaceChoicePanel
     */
    public DragonbornOptionalRaceChoicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        dragonColorField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        damageTypeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        breathWeaponField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Draconic ancestor");

        jToggleButton1.setText("Choose color");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Color");

        dragonColorField.setEditable(false);

        jLabel3.setText("Damage type");

        damageTypeField.setText("");
        damageTypeField.setEditable(false);

        jLabel4.setText("Breath Weapon");

        breathWeaponField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(dragonColorField, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(damageTypeField)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(breathWeaponField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(11, 11, 11)
                .addComponent(dragonColorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(damageTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breathWeaponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        DragonColorSelectionWindow lvDragonColorFrame = new DragonColorSelectionWindow(this);
        lvDragonColorFrame.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void setFieldsValues(DraconicAncestorColor pmColor, DamageType pmResistance, AutomaterAttack pmAttack)
    {
        dragonColorField.setText(pmColor.toString());
        
        mSelectedColor = pmColor;
        
        damageTypeField.setText(pmResistance.toString());
        
        mDamageType = pmResistance;
        
        breathWeaponField.setText(pmAttack.toFieldString());
        
        mAttack = pmAttack;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField breathWeaponField;
    private javax.swing.JTextField damageTypeField;
    private javax.swing.JTextField dragonColorField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
