/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.enums.Tools;
import com.blogspot.gameeaterpl.ui.panels.windows.BasicSelectionWindow;
import com.blogspot.gameeaterpl.ui.panels.windows.ToolsSelectionWindowOpener;
import java.util.HashMap;
import java.util.List;
import javax.swing.AbstractListModel;

/**
 *
 * @author Sakurazuka
 */
public class DwarfOptionalRaceChoicePanel extends javax.swing.JPanel implements ToolsSelectionWindowOpener {

    /**
     * Creates new form DwarfOptionalRaceChoicePanel
     */
    public DwarfOptionalRaceChoicePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        toolProficiencyField = new javax.swing.JTextField();
        chooseToolProficiencyButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Choose one tool proficiency");

        chooseToolProficiencyButton.setText("Choose");
        chooseToolProficiencyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseToolProficiencyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chooseToolProficiencyButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(toolProficiencyField, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolProficiencyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseToolProficiencyButton)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        toolProficiencyField.setEditable(false);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseToolProficiencyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseToolProficiencyButtonActionPerformed
        AbstractListModel lvModel = new javax.swing.AbstractListModel() {
            Tools[] tools = {Tools.BREWERS_SUPPLIES, Tools.MASONS_TOOLS, Tools.SMITHS_TOOLS};
            @Override
            public int getSize() { return tools.length; }
            @Override
            public Object getElementAt(int i) { return tools[i]; }
        };
        
        HashMap<Object,String> lvToolsDescriptions = new HashMap<>();
        lvToolsDescriptions.put(Tools.BREWERS_SUPPLIES, "");
        lvToolsDescriptions.put(Tools.MASONS_TOOLS, "");
        lvToolsDescriptions.put(Tools.SMITHS_TOOLS, "");
        
        BasicSelectionWindow lvWindow = new BasicSelectionWindow(1, 1, lvModel, lvToolsDescriptions, "Tool proficiency", "Tool proficiencies", (ToolsSelectionWindowOpener)this);
       
        lvWindow.setVisible(true);
    }//GEN-LAST:event_chooseToolProficiencyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseToolProficiencyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField toolProficiencyField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setToolsFields(List<Tools> pmToolsList) {
        toolProficiencyField.setText(pmToolsList.get(0).toString());
    }
}
