/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.character.CharacterChoiceContainer;
import com.blogspot.gameeaterpl.enums.Languages;
import com.blogspot.gameeaterpl.enums.Tools;
import com.blogspot.gameeaterpl.ui.panels.windows.BasicSelectionWindow;
import com.blogspot.gameeaterpl.ui.panels.windows.LanguagesSelectionWindowOpener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.AbstractListModel;

/**
 *
 * @author Sakurazuka
 */
public class ElfOptionalRaceChoicePanel extends javax.swing.JPanel implements LanguagesSelectionWindowOpener, SpecialChoicePanelInterface {

    private Languages mChosenLanguage;
    /**
     * Creates new form ElfOptionalRaceChoicePanel
     */
    public ElfOptionalRaceChoicePanel() {
        initComponents();
    }
    
    public void setControlsEnabled(boolean isEnabled)
    {
        cantripField.setEnabled(isEnabled);
        languageField.setEnabled(isEnabled);
        chooseCantripButton.setEnabled(isEnabled);
        chooseLanguageButton.setEnabled(isEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cantripField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        languageField = new javax.swing.JTextField();
        chooseCantripButton = new javax.swing.JToggleButton();
        chooseLanguageButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Choose one Wizard Cantrip*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Choose one Language*");

        chooseCantripButton.setText("Choose");

        chooseLanguageButton.setText("Choose");
        chooseLanguageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseLanguageButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("*only for High Elf Subrace");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cantripField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseCantripButton))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseLanguageButton)))))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantripField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseCantripButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(languageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseLanguageButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        cantripField.setEditable(false);
        languageField.setEditable(false);
        languageField.setEnabled(false);
        chooseCantripButton.setEnabled(false);
        chooseLanguageButton.setEnabled(false);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseLanguageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseLanguageButtonActionPerformed
        ArrayList<Languages> lvList;
        lvList = Languages.toList();
        lvList.remove(Languages.COMMON);
        lvList.remove(Languages.ELVISH);

        AbstractListModel lvModel = new javax.swing.AbstractListModel() {
            Languages[] languages = new Languages[lvList.size()];

            {
                this.languages = lvList.toArray(languages);
            }

            @Override
            public int getSize() {
                return languages.length;
            }

            @Override
            public Object getElementAt(int i) {
                return languages[i];
            }
        };

        HashMap<Object, String> lvSkillsDescriptions = new HashMap<>();

        for (Languages lvLanguage : lvList) {
            lvSkillsDescriptions.put(lvLanguage, "");
        }
        BasicSelectionWindow lvWindow = new BasicSelectionWindow(1, 1, lvModel, lvSkillsDescriptions, "Language", "Languages", (LanguagesSelectionWindowOpener) this);

        lvWindow.setVisible(true);
    }//GEN-LAST:event_chooseLanguageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantripField;
    private javax.swing.JToggleButton chooseCantripButton;
    private javax.swing.JButton chooseLanguageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField languageField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setLanguagesFields(List<Languages> pmLanguagesList) {
        languageField.setText(pmLanguagesList.get(0).toString());
        mChosenLanguage = pmLanguagesList.get(0);
    }

    @Override
    public CharacterChoiceContainer getChoiceContainer() {
        CharacterChoiceContainer lvChoiceValues = new CharacterChoiceContainer();
        
        if(languageField.isEnabled() && cantripField.isEnabled())
        {
            ArrayList<Languages> lvLanguagesList = new ArrayList<>();
        HashMap<Integer,ArrayList<Languages>> lvLanguagesMap = new HashMap<>();
        
        if(mChosenLanguage != null)
        lvLanguagesList.add(mChosenLanguage);
        
        lvLanguagesMap.put(1, lvLanguagesList);
        
        lvChoiceValues.setmLanguages(lvLanguagesMap);
        }
        
        
        return lvChoiceValues;
    }
}
