/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.enums.Abilities;
import com.blogspot.gameeaterpl.enums.Skills;
import com.blogspot.gameeaterpl.ui.panels.windows.AbilitiesSelectionWindowOpener;
import com.blogspot.gameeaterpl.ui.panels.windows.BasicSelectionWindow;
import com.blogspot.gameeaterpl.ui.panels.windows.SkillsSelectionWindowOpener;
import com.blogspot.gameeaterpl.utils.FileUtils;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;

/**
 *
 * @author sakurazuka
 */
public class HumanOptionalRaceChoicePanel extends javax.swing.JPanel implements AbilitiesSelectionWindowOpener, SkillsSelectionWindowOpener {

    HashMap<Abilities, Integer> mAbilities;
    Skills mSkill;

    /**
     * Creates new form HumanOptionalRaceChoicePanel
     */
    public HumanOptionalRaceChoicePanel() {
        initComponents();
        mAbilities = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        abilityField1 = new javax.swing.JTextField();
        abilityField2 = new javax.swing.JTextField();
        skillField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Human race bonusses");

        jRadioButton1.setText("+1 to all Abilities");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jRadioButton1.setSelected(true);

        jRadioButton2.setText("+1 to two Abilities, 1 Skill proficiency and 1 Feat");
        jRadioButton2.setSelected(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Choose 2 Abilities ");

        jLabel3.setText("Choose 1 Skill");

        jLabel4.setText("Choose 1 Feat");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setEnabled(false);

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jRadioButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(abilityField1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox4, javax.swing.GroupLayout.Alignment.LEADING, 0, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(abilityField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(skillField1, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abilityField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abilityField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skillField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        abilityField1.setEditable(false);
        abilityField2.setEditable(false);
        skillField1.setEditable(false);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //AbillitiesSelectionWindow lvWindow = new AbillitiesSelectionWindow(2, 2, this);
        AbstractListModel lvModel = new javax.swing.AbstractListModel() {
            Abilities[] abilities = {Abilities.STRENGTH, Abilities.CONSTITUTION, Abilities.DEXTERITY, Abilities.INTELIGENCE, Abilities.WISDOM, Abilities.CHARISMA};

            @Override
            public int getSize() {
                return abilities.length;
            }

            @Override
            public Object getElementAt(int i) {
                return abilities[i];
            }
        };

        HashMap<Object, String> lvAbilitiesDescriptions = new HashMap<>();

        try {
            lvAbilitiesDescriptions.put(Abilities.STRENGTH, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "StrengthAbilityDescription.txt"), StandardCharsets.UTF_8));
            lvAbilitiesDescriptions.put(Abilities.CONSTITUTION, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "ConstitutionAbilityDescription.txt"), StandardCharsets.UTF_8));
            lvAbilitiesDescriptions.put(Abilities.DEXTERITY, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "DexterityAbilityDescription.txt"), StandardCharsets.UTF_8));
            lvAbilitiesDescriptions.put(Abilities.INTELIGENCE, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "InteligenceAbilityDescription.txt"), StandardCharsets.UTF_8));
            lvAbilitiesDescriptions.put(Abilities.WISDOM, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "WisdomAbilityDescription.txt"), StandardCharsets.UTF_8));
            lvAbilitiesDescriptions.put(Abilities.CHARISMA, FileUtils.readFile(this.getClass().getResource(FileUtils.DESCRIPTION_URL + "CharismaAbilityDescription.txt"), StandardCharsets.UTF_8));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(FileUtils.class.getName()).log(Level.SEVERE, null, ex);
        }

        BasicSelectionWindow lvWindow = new BasicSelectionWindow(2, 2, lvModel, lvAbilitiesDescriptions, "Ability", "Abilities", (AbilitiesSelectionWindowOpener) this);

        lvWindow.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<Skills> lvList;
        lvList = Skills.toList();

        AbstractListModel lvModel = new javax.swing.AbstractListModel() {
            Skills[] skills = new Skills[lvList.size()];

            {
                this.skills = lvList.toArray(skills);
            }

            @Override
            public int getSize() {
                return skills.length;
            }

            @Override
            public Object getElementAt(int i) {
                return skills[i];
            }
        };

        HashMap<Object, String> lvSkillsDescriptions = new HashMap<>();

        for (Skills lvSkill : lvList) {
            lvSkillsDescriptions.put(lvSkill, "");
        }
        BasicSelectionWindow lvWindow = new BasicSelectionWindow(1, 1, lvModel, lvSkillsDescriptions, "Skill", "Skills", (SkillsSelectionWindowOpener) this);

        lvWindow.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abilityField1;
    private javax.swing.JTextField abilityField2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField skillField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAbilitiesFields(List<Abilities> pmAbilitiesList) {
        abilityField1.setText(pmAbilitiesList.get(0).toString());
        abilityField2.setText(pmAbilitiesList.get(1).toString());

        mAbilities.put(pmAbilitiesList.get(0), 1);
        mAbilities.put(pmAbilitiesList.get(1), 1);
    }

    @Override
    public void setSkillsFields(List<Skills> pmAbilitiesList) {
        skillField1.setText(pmAbilitiesList.get(0).toString());
        mSkill = pmAbilitiesList.get(0);
    }
}
