/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.character.Races;
import com.blogspot.gameeaterpl.utils.FileUtils;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;


/**
 *
 * @author sakurazuka
 */
public class RaceDescriptionPanel extends javax.swing.JPanel {

    HashMap<Races,String> mPictureLinks;
    HashMap<Races,String> mDescriptionLinks;
    private final String mBackgroundUrl = "/com/blogspot/gameeaterpl/ui/panels/images/";
    BufferedImage img;
    File mFile;

    /**
     * Creates new form RaceDescriptionPanel
     */
    public RaceDescriptionPanel() {
        
        initializePictureLinks();
        initializeDescriptions();
        /*try {
           img = ImageIO.read(getClass().getResource(mPictureLinks.get(Races.DWARF)));
        } catch (IOException e) {
            e.printStackTrace();
        }*/
        
        initComponents();
        
        switchDescription(Races.DWARF);
    }
    
    //public RaceDescriptionPanel(String)
    
    private void initializePictureLinks()
    {
        mPictureLinks = new HashMap<>();
        mPictureLinks.put(Races.ELF, mBackgroundUrl+"rElf.jpg");
        mPictureLinks.put(Races.DWARF, mBackgroundUrl + "rDwarf.jpg");
        mPictureLinks.put(Races.HALFLING, mBackgroundUrl + "rHalfling.jpg");
        mPictureLinks.put(Races.DRAGONBORN, mBackgroundUrl+"rDragonborn.jpg");
        mPictureLinks.put(Races.GNOME, mBackgroundUrl+"rElf.jpg");
        mPictureLinks.put(Races.HALFELF, mBackgroundUrl+"rElf.jpg");
        mPictureLinks.put(Races.HALFORC, mBackgroundUrl+"rElf.jpg");
        mPictureLinks.put(Races.HUMAN, mBackgroundUrl+"rElf.jpg");
        
    }
    
    private void initializeDescriptions()
    {
        mDescriptionLinks = new HashMap<>();
        mDescriptionLinks.put(Races.ELF, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.DWARF, FileUtils.DESCRIPTION_URL + "DwarfRaceDescription.txt");
        mDescriptionLinks.put(Races.HALFLING, FileUtils.DESCRIPTION_URL + "EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.DRAGONBORN, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.GNOME, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.HALFELF, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.HALFORC, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        mDescriptionLinks.put(Races.HUMAN, FileUtils.DESCRIPTION_URL+"EmptyRaceDescription.txt");
        
        
    }
    
    public final void switchDescription(Races pmRace)
    {
        try {
           img = ImageIO.read(getClass().getResource(mPictureLinks.get(pmRace)));
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        this.repaint();
        
        try {
            this.raceDescriptionTextArea1.setText(FileUtils.readFile(this.getClass().getResource(mDescriptionLinks.get(pmRace)), StandardCharsets.UTF_8));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(RaceDescriptionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public Dimension getPreferredSize() {
        if (img == null) {
            return new Dimension(500, 508);
        } else {
            return new Dimension(img.getWidth(null), img.getHeight(null));
        }
    }

    
    
    @Override
    protected void paintComponent(Graphics g) {

        g.drawImage(img, 0, 0, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        raceDescriptionTextArea1 = new com.blogspot.gameeaterpl.ui.RaceDescriptionTextArea();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setBackground(new Color(0, 0, 0, 0));

        raceDescriptionTextArea1.setBackground(new Color(0,0,0,0));
        raceDescriptionTextArea1.setColumns(20);
        raceDescriptionTextArea1.setLineWrap(true);
        raceDescriptionTextArea1.setRows(5);
        raceDescriptionTextArea1.setText("Dupa elfki jest zajebista. Niestety elfki nie posiadają satysfakcjonujących cycków.");
        raceDescriptionTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(raceDescriptionTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.blogspot.gameeaterpl.ui.RaceDescriptionTextArea raceDescriptionTextArea1;
    // End of variables declaration//GEN-END:variables
}
