/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import java.awt.Graphics;
import java.awt.Dimension;
import java.io.File;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;

/**
 *
 * @author sakurazuka
 */
public class RaceDescriptionPanel extends javax.swing.JPanel {

    private String mBackgroundUrl = "/com/blogspot/gameeaterpl/ui/panels/images/rElf.jpg";
    BufferedImage img;

    /**
     * Creates new form RaceDescriptionPanel
     */
    public RaceDescriptionPanel() {
        try {
           img = ImageIO.read(getClass().getResource(mBackgroundUrl));
        } catch (IOException e) {
            e.printStackTrace();
        }
        initComponents();
    }

    @Override
    public Dimension getPreferredSize() {
        if (img == null) {
            return new Dimension(500, 508);
        } else {
            return new Dimension(img.getWidth(null), img.getHeight(null));
        }
    }

    @Override
    protected void paintComponent(Graphics g) {

        g.drawImage(img, 0, 0, null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        raceDescriptionTextArea1 = new com.blogspot.gameeaterpl.ui.RaceDescriptionTextArea();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setBackground(new Color(0, 0, 0, 0));

        raceDescriptionTextArea1.setBackground(new Color(0,0,0,0));
        raceDescriptionTextArea1.setColumns(20);
        raceDescriptionTextArea1.setLineWrap(true);
        raceDescriptionTextArea1.setRows(5);
        raceDescriptionTextArea1.setText("Dupa elfki jest zajebista. Niestety elfki nie posiadają satysfakcjonujących cycków.");
        raceDescriptionTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(raceDescriptionTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.blogspot.gameeaterpl.ui.RaceDescriptionTextArea raceDescriptionTextArea1;
    // End of variables declaration//GEN-END:variables
}
