/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.blogspot.gameeaterpl.ui.panels;

import com.blogspot.gameeaterpl.character.Character;
import com.blogspot.gameeaterpl.enums.Races;
import com.blogspot.gameeaterpl.character.Subraces;
import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author sakurazuka
 */
public class RaceChosePanel extends javax.swing.JPanel implements CharacterCreatorPanel {

    HashMap<Races, ArrayList<Subraces>> mSubraceToRaceConnection;

    /**
     * Creates new form RaceChosePanel
     */
    public RaceChosePanel() {

        initSubraces();
        initComponents();
    }

    private void initSubraces() {

        ArrayList<Subraces> lvTempList = new ArrayList<>();
        mSubraceToRaceConnection = new HashMap<>();

        lvTempList.add(Subraces.MOUNTAINDWARF);
        lvTempList.add(Subraces.HILLDWARF);
        mSubraceToRaceConnection.put(Races.DWARF, lvTempList);

        lvTempList = new ArrayList<>();
        lvTempList.add(Subraces.LOGHTFOOTHALFLING);
        lvTempList.add(Subraces.STOUTHALFLING);
        mSubraceToRaceConnection.put(Races.HALFLING, lvTempList);

        lvTempList = new ArrayList<>();
        lvTempList.add(Subraces.ROCKGNOME);
        lvTempList.add(Subraces.FORESTGNOME);
        mSubraceToRaceConnection.put(Races.GNOME, lvTempList);

        lvTempList = new ArrayList<>();
        lvTempList.add(Subraces.HIGHELF);
        lvTempList.add(Subraces.WOODELF);
        lvTempList.add(Subraces.DARKELF);
        mSubraceToRaceConnection.put(Races.ELF, lvTempList);

        lvTempList = new ArrayList<>();
        lvTempList.add(Subraces.NONE);
        mSubraceToRaceConnection.put(Races.DRAGONBORN, lvTempList);
        mSubraceToRaceConnection.put(Races.HALFORC, lvTempList);
        mSubraceToRaceConnection.put(Races.HALFELF, lvTempList);
        mSubraceToRaceConnection.put(Races.HUMAN, lvTempList);
        mSubraceToRaceConnection.put(Races.TIEFLING, lvTempList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        racesComboBox = new javax.swing.JComboBox();
        showPictureButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        subracesComboBox = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        raceDescriptionPanel1 = new com.blogspot.gameeaterpl.ui.panels.RaceDescriptionPanel();
        raceSpecialChoicePanel1 = new com.blogspot.gameeaterpl.ui.panels.RaceSpecialChoicePanel();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Races");

        jLabel2.setText("Race:");

        ArrayList<Races> lvTempNamesList = new ArrayList<>();

        for(Races al : Races.values())
        {
            lvTempNamesList.add(al);
        }
        racesComboBox.setModel(new javax.swing.DefaultComboBoxModel(lvTempNamesList.toArray()));
        racesComboBox.setSelectedItem(Races.DWARF);
        racesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racesComboBoxActionPerformed(evt);
            }
        });

        showPictureButton.setText(">>");
        showPictureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPictureButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Subrace:");

        subracesComboBox.setModel(new javax.swing.DefaultComboBoxModel(mSubraceToRaceConnection.get((Races)racesComboBox.getSelectedItem()).toArray()));
        subracesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subracesComboBoxActionPerformed(evt);
            }
        });

        jButton2.setText(">>");

        raceSpecialChoicePanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subracesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(racesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPictureButton))
                    .addComponent(jLabel3)
                    .addComponent(raceSpecialChoicePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(raceDescriptionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(racesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPictureButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subracesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(raceSpecialChoicePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(raceDescriptionPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showPictureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPictureButtonActionPerformed
        raceDescriptionPanel1.switchDescription((Races) racesComboBox.getSelectedItem());
    }//GEN-LAST:event_showPictureButtonActionPerformed

    private void racesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racesComboBoxActionPerformed
        
        //Ustawiamy zawartość combo podras
        ArrayList<Subraces> lvSelectedList = mSubraceToRaceConnection.get((Races)racesComboBox.getSelectedItem());
        subracesComboBox.setModel(new javax.swing.DefaultComboBoxModel(lvSelectedList.toArray()));
        if(lvSelectedList.size()==1)
        {
            subracesComboBox.setEnabled(false);
        }else{
            if(!subracesComboBox.isEnabled())
                subracesComboBox.setEnabled(true);
        }
        
        //Wyświetlamy obrazek
        raceDescriptionPanel1.switchDescription((Races) racesComboBox.getSelectedItem());
        //Wyświetlamy sekcję dodatkową (jeśli potrzebna)
        raceSpecialChoicePanel1.switchCardByRace((Races) racesComboBox.getSelectedItem());
        //Sprawdzamy czy nie włączyła się podrasa HighElfa (przy przełączeniu na Elfa)
        raceSpecialChoicePanel1.setControlsEnabledBySubrace((Subraces)subracesComboBox.getSelectedItem());
    }//GEN-LAST:event_racesComboBoxActionPerformed

    private void subracesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subracesComboBoxActionPerformed
        raceSpecialChoicePanel1.setControlsEnabledBySubrace((Subraces)subracesComboBox.getSelectedItem());
    }//GEN-LAST:event_subracesComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.blogspot.gameeaterpl.ui.panels.RaceDescriptionPanel raceDescriptionPanel1;
    private com.blogspot.gameeaterpl.ui.panels.RaceSpecialChoicePanel raceSpecialChoicePanel1;
    private javax.swing.JComboBox racesComboBox;
    private javax.swing.JButton showPictureButton;
    private javax.swing.JComboBox subracesComboBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void fillCharacterObject(Character pmCharacter) {
        
        ((RaceSpecialChoicePanelInterface)raceSpecialChoicePanel1).addRace(pmCharacter, (Races)racesComboBox.getSelectedItem(), (Subraces)subracesComboBox.getSelectedItem());

    }
}
